### ISSUE TITLE
 callback from lua_register()

### ISSUE THREAD

**Issue by AndreiRudenko** [AndreiRudenko/linc_luajit#1]
I didnt know how to make callbacks directly from lua_register function. But i found some examples in linc_sdl and linc_ogg. 
[SDL init_event_watch() cpp](https://github.com/snowkit/linc_sdl/blob/master/linc/linc_sdl.cpp#L639)
[SDL init_event_watch() hx](https://github.com/snowkit/linc_sdl/blob/master/sdl/SDL.hx#L1347)
they are using StringMap and after any callback searching by id in Map.
Is there way to set callback directly to function.
there is cpp function whitch works with lua_register()

```
        static int luaCallback(lua_State *L){
            return 0;
        }
```

[linc_lua lua_register() hx](https://github.com/RudenkoArt/linc_lua/blob/master/lua/Lua.hx#L203)
Is there way to do it with haxe ?

upd:
also there is example of callback from hx-lua [haxe_callback](https://github.com/RudenkoArt/hx-lua/blob/master/project/common/ExternalInterface.cpp#L125) & [func decl](https://github.com/RudenkoArt/hx-lua/blob/master/project/common/ExternalInterface.cpp#L206)
and with this wrapper i can make callback like this:

```
        lua.setVars( {
            GetEntityPos:
                function(_name:String) {
                    var ent:Entity = Luxe.scene.get(_name);
                    return { x : ent.pos.x, y : ent.pos.y};
                }
        });
        lua.setVars( {
            SetEntityPos:
                function(_name:String, _x:Float, _y:Float) {
                    var ent:Entity = Luxe.scene.get(_name);
                    ent.pos.set_xy(_x, _y);
                }
        });
```

and this is works well with variable numbers of arguments
i was looking in hxcpp what is he doing with variable arguments, and looks like he pushing in haxe "stack" (like in lua) arguments and then call function.
What i want, is just make linc_lua work just like with hxcpp AutoGCRoot with callbacks.

I can make callback from lua, and in haxe get function from StringMap by name. But i dont know how to call functions with variable number of arguments. And maybe is there another better way.

**Comment by RudenkoArt** [comment]
also there is example of callback from hx-lua [haxe_callback](https://github.com/RudenkoArt/hx-lua/blob/master/project/common/ExternalInterface.cpp#L125)

**Comment by AndreiRudenko** [comment]
i was trying to make callbacks, so there is [callback_handler](https://github.com/RudenkoArt/linc_lua/blob/master/lua/Lua.hx#L401)

```
        lua.setFunction("callBack", 
            function(a:String, b:Float) {
                trace("callBack function called! : " + a + " " + b);
                return 123;
            }
        );
```

not elegant, but works :)
