### ISSUE TITLE
macOS build errors

### ISSUE THREAD

**Issue by ghost** [AndreiRudenko/linc_luajit#10]
what if i send you the errors that i get on my macos then you can fix it

**Comment by AndreiRudenko** [comment]
Yes, send it here, maybe we can resolve them

**Comment by ghost** [comment]
with my errors and your smartness we can do anything

**Comment by ghost** [comment]
also when we fix and resolve these issues cause you make the version 4.0.0

**Comment by ghost** [comment]
on the haxelib website

**Comment by ghost** [comment]
also

**Comment by ghost** [comment]
do you have discord?

**Comment by AndreiRudenko** [comment]
Just paste here error log

**Comment by ghost** [comment]
oh so you don't have discord 
?

**Comment by ghost** [comment]
also the error that i get is from fnf so

**Comment by ghost** [comment]
also bro your the main reason why we port to lua on friday night funkin

**Comment by AndreiRudenko** [comment]
Thank you! Please pack next one to one message so we can easily navigate in this issue messages. 

As far as i know, lua jit version have issues on mac and consoles (we have discussion on Kha discord), and it didnt updates for a long time. 
If we cant resolve it here, maybe some other guys who more experienced with mac stuff can help with it. 

But my recomendation is to use latest version of lua without jit. 
Curently im not planning to make non jit version, but there is a lib by [kevinresol](https://github.com/kevinresol) [linc_lua](https://github.com/kevinresol/linc_lua) this can do the job. If not, we can make PR to fix issues in his lib.

Anyway please paste the error log, so we can se what is wrong ;)

**Comment by ghost** [comment]
ok bet

**Comment by AndreiRudenko** [comment]
Looks like all traffic that i have is from Kade engine, i didnt know that, i really appreciate that they using my lib, but changes need to be made. So i will make lua without jit version when i have some spare time, it will be slower but more stable, and works on consoles.

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
i think it whould be better

**Comment by ghost** [comment]
but yeah do what you want to do no on is gonna stop you

**Comment by AndreiRudenko** [comment]
But i also make issue on Kade engine with suggestion to port from my lib to Kevin [linc_lua](https://github.com/kevinresol/linc_lua). As it works well on macOS as we can se it here https://github.com/kevinresol/hxvm-lua

**Comment by ghost** [comment]
did he respond back?

**Comment by ghost** [comment]
kade

**Comment by AndreiRudenko** [comment]
Just opened it, we will see if it helps.

**Comment by ghost** [comment]
In file included from ./src/__boot__.cpp:770:
In file included from include/llua/Lua_helper.h:11:
/usr/local/lib/haxe/lib/linc_luajit/git//linc/linc_lua.h:12:10: warning: non-portable path to file '"../lib/lua/src/lua.hpp"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "../lib/Lua/src/lua.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~
         "../lib/lua/src/lua.hpp"
1 warning generated.

**Comment by ghost** [comment]
In file included from ./src/llua/Lua_helper.cpp:6:
/usr/local/lib/haxe/lib/linc_luajit/git//linc/linc_lua.h:12:10: warning: non-portable path to file '"../lib/lua/src/lua.hpp"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "../lib/Lua/src/lua.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~
         "../lib/lua/src/lua.hpp"
1 warning generated.

**Comment by ghost** [comment]
In file included from ./src/llua/Convert.cpp:6:
/usr/local/lib/haxe/lib/linc_luajit/git//linc/linc_lua.h:12:10: warning: non-portable path to file '"../lib/lua/src/lua.hpp"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "../lib/Lua/src/lua.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~
         "../lib/lua/src/lua.hpp"
1 warning generated.

**Comment by AndreiRudenko** [comment]
Yes, static libs in this [folder](https://github.com/AndreiRudenko/linc_luajit/tree/master/lib/lua/lib/Mac) need to be same version as your current system

**Comment by AndreiRudenko** [comment]
Yes, please rebuild static libs in this folder to match system version https://github.com/AndreiRudenko/linc_luajit/tree/master/lib/lua/lib/Mac

**Comment by ghost** [comment]
and thats it

**Comment by ghost** [comment]
there is your error log

**Comment by AndreiRudenko** [comment]
Please tell me if it fixes your issue, haxelib version are updated as well.
And also please dont make many messages here as its not a chat, pack it to one message.
Thank you

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
/usr/local/lib/haxe/lib/linc_luajit/git/linc/linc_lua.cpp:65:25: warning: comparison of array 'dbg.short_src' not equal to a null pointer is always true [-Wtautological-pointer-compare]
                if (dbg.short_src != NULL) {
                    ~~~~^~~~~~~~~    ~~~~
/usr/local/lib/haxe/lib/linc_luajit/git/linc/linc_lua.cpp:69:37: warning: comparison between NULL and non-pointer ('int' and NULL) [-Wnull-arithmetic]
                if (dbg.linedefined != NULL) {
                    ~~~~~~~~~~~~~~~ ^  ~~~~
/usr/local/lib/haxe/lib/linc_luajit/git/linc/linc_lua.cpp:73:41: warning: comparison between NULL and non-pointer ('int' and NULL) [-Wnull-arithmetic]
                if (dbg.lastlinedefined != NULL) {
                    ~~~~~~~~~~~~~~~~~~~ ^  ~~~~
/usr/local/lib/haxe/lib/linc_luajit/git/linc/linc_lua.cpp:94:37: warning: comparison between NULL and non-pointer ('int' and NULL) [-Wnull-arithmetic]
                if (dbg.currentline != NULL) {
                    ~~~~~~~~~~~~~~~ ^  ~~~~
/usr/local/lib/haxe/lib/linc_luajit/git/linc/linc_lua.cpp:100:30: warning: comparison between NULL and non-pointer ('int' and NULL) [-Wnull-arithmetic]
                if (dbg.nups != NULL) {
                    ~~~~~~~~ ^  ~~~~
5 warnings generated.

**Comment by ghost** [comment]
there is more errors

**Comment by ghost** [comment]
also

**Comment by ghost** [comment]
ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(ljamalg.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(lj_vm.o)) was built for newer macOS version (11.0) than being linked (10.9)

**Comment by ghost** [comment]
so idk if i need to get the newer file so

**Comment by isakube** [comment]
> ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(ljamalg.o)) was built for newer macOS version (11.0) than being linked (10.9) ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(lj_vm.o)) was built for newer macOS version (11.0) than being linked (10.9)

you're on Big Sur (11.0). It's trying to compile for ~~Catalina (10.9) i believe~~ Wait a second... 10.9 is MAVERICKS. (I thought it was Catalina oop)

Why is it being linked for Mavericks??? that's from, like, 2013. Unless these numbers aren't actually the OS version, and 10.9 is Catalina. That would make more sense.

**Comment by gaminbottomtext** [comment]
> > ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(ljamalg.o)) was built for newer macOS version (11.0) than being linked (10.9) ld: warning: object file (/usr/local/lib/haxe/lib/linc_luajit/git//lib/lua/lib/Mac/libluajit-5.1.a(lj_vm.o)) was built for newer macOS version (11.0) than being linked (10.9)
> 
> you're on Big Sur (11.0). It's trying to compile for ~Catalina (10.9) i believe~ Wait a second... 10.9 is MAVERICKS. (I thought it was Catalina oop)
> 
> Why is it being linked for Mavericks??? that's from, like, 2013. Unless these numbers aren't actually the OS version, and 10.9 is Catalina. That would make more sense.

I have no idea, i would try to rebuild the static libs as i am on big sur butttttt, i have no idea how to

**Comment by isakube** [comment]
> I have no idea, i would try to rebuild the static libs as i am on big sur butttttt, i have no idea how to

cool i dont either :kubeSuffer:

**Comment by gaminbottomtext** [comment]
:trollface:

**Comment by gaminbottomtext** [comment]
@prokube i fixed linc_luajit for mac

**Comment by gaminbottomtext** [comment]
i found another .a file that worked

**Comment by gaminbottomtext** [comment]
I made a pull request, hope he merges
