### ISSUE TITLE
is it nessicary for there to be libs?

### ISSUE THREAD

**Issue by ghost** [AndreiRudenko/linc_luajit#13]
cause i think you don't really need the libs i think its just that you need only the paths

**Comment by AndreiRudenko** [comment]
If you think that we dont need static libs that linked. Here is why we do need https://luajit.org/install.html and quote from luajit creator from embedding jit: "It's strongly suggested to build LuaJIT separately using the supplied build system. Please do not attempt to integrate the individual source files into your build tree."
