### ISSUE TITLE
Cannot access lua package while targeting cpp

### ISSUE THREAD

**Issue by gmisail** [AndreiRudenko/linc_luajit#2]
I get this error when building the "test" project. Aren't you supposed to target cpp?

**Comment by AndreiRudenko** [comment]
@gmisail64 Hey, thanks! fixed :) You need to clone and set lib folder:  `haxelib dev linc_luajit C:/github/linc_luajit` Target is cpp only for now.

**Comment by gmisail** [comment]
@RudenkoArts I think you will need to change the name of the lua.\* namespace. It conflicts with the lua haxe target I believe.

**Comment by AndreiRudenko** [comment]
@gmisail64 hm, thanks, great idea.
