### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by VMan-2002** [AndreiRudenko/linc_luajit#22]
Add documentation

**Comment by VMan-2002** [comment]
please

**Comment by AndreiRudenko** [comment]
Hey! You can use any other lua wrappers that writen in C language, or C++ to understand how it can be used. The API that we have here is just a translation from C language. As for haxe, there is basic example in test folder.
Here is official documentation that can be very helpful https://www.lua.org/manual/5.1/manual.html#3
