### ISSUE TITLE
Missing Linux and Mac libs

### ISSUE THREAD

**Issue by AndreiRudenko** [AndreiRudenko/linc_luajit#3]
If someone have compiled luajit on linux or mac, please send me files or make pr. Thanks ;)

**Comment by AndreiRudenko** [comment]
#7

**Comment by ghost** [comment]
i can help

**Comment by ghost** [comment]
but it always give's me error's when i try to build it 
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [luajit] Error 1
make: *** [default] Error 2

**Comment by ghost** [comment]
also im on mac
