### ISSUE TITLE
Crash on callback run

### ISSUE THREAD

**Issue by mikaib** [AndreiRudenko/linc_luajit#32]
Hello!

linc_luajit works fine, and I'm able to run some stuff (``like print("hello world!") or print(5+5)``) 
But then I add a callback as such:

```
var vm:State = LuaL.newstate();
LuaL.openlibs(vm);

 Lua_helper.add_callback(vm, "test", function() {
    return 2 + 2;
 });
 ```
 
after which it crashes the application without any visibile error.
i can do ``print(test)`` which will return something like "function: 0x0cd84058"
but calling it causes it to crash.
I don't know where to even start debugging this or collecting information that could possibly help debug this.

With kind regards,

**Comment by AndreiRudenko** [comment]
Hello!
Try to call Lua.init_callbacks(vm); after LuaL.openlibs(vm);
I think it should work.

**Comment by mikaib** [comment]
Yup, that was indeed the problem, thank you!
