### ISSUE TITLE
Updating linc_luajit!

### ISSUE THREAD

**Issue by Fla-man-OFFICIAL** [AndreiRudenko/linc_luajit#37]
So I have the sorce code of a game and it needs linc_luajit and when i try and update it it just stuck on "Updating linc_luajit version git ..."
And thats it
![image_2024-08-26_225305408](https://github.com/user-attachments/assets/4b096f30-d75e-45ff-bafa-c6d6842779c2)

**Comment by Fla-man-OFFICIAL** [comment]
Help me!

**Comment by AndreiRudenko** [comment]
Hello, I updated version in haxelib and updated link to github in config file, should be working now. https://lib.haxe.org/p/linc_luajit/
