### ISSUE TITLE
With Haxe there is issue

### ISSUE THREAD

**Issue by ghost** [AndreiRudenko/linc_luajit#5]
In some files it tries importing ../lib/lua/...
L in Lua needs to be capitalised for it to work

**Comment by ghost** [comment]
oh nice, it happened in 2 files by the way

**Comment by AndreiRudenko** [comment]
Hmm, i think i checked all, can you point me to that file?

**Comment by ghost** [comment]
I found:
`linc_luajit/0,0,2/linc/linc_lua.cpp`
and
`linc_luajit/0,0,2//linc/linc_lua.h`

**Comment by AndreiRudenko** [comment]
The paths is fixed, i found in one file only [here](https://github.com/AndreiRudenko/linc_luajit/blob/master/linc/linc_lua.h#L10), but [here](https://github.com/AndreiRudenko/linc_luajit/blob/master/linc/linc_lua.cpp#L6) was ok. Can you update and check if any errors still appears?

**Comment by ghost** [comment]
updated and error fixed, other error still happens
