### ISSUE TITLE
HTML5 compilation

### ISSUE THREAD

**Issue by ghost** [AndreiRudenko/linc_luajit#6]
I can't compile to HTML5, get this error:
```
/usr/share/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:492: characters 43-61 : Abstract<cpp.Callable> has no field fromStaticFunction
/usr/share/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:526: characters 42-60 : Abstract<cpp.Callable> has no field fromStaticFunction
```

**Comment by AndreiRudenko** [comment]
The library works on Haxe/hxcpp target only, and also not on Haxe/hashlink.

**Comment by ghost** [comment]
I'm just trying to compile an FNF modding framework (https://github.com/aflacc/ProjectFNF) and it gives that error what do i do

**Comment by AndreiRudenko** [comment]
Just use it for native cpp target

**Comment by ghost** [comment]
I don't know what tht means

**Comment by AndreiRudenko** [comment]
Haxe has many targets, it just translates your haxe code to Java, C++, JS, and many others [look here](https://haxe.org/documentation/introduction/compiler-targets.html)

**Comment by ghost** [comment]
By native cpp do you mean Linux in my case? I get other error when trying that

**Comment by AndreiRudenko** [comment]
That kind of errors? Did sample project works on Linux?

**Comment by ghost** [comment]
Linux has different error, will paste in a minute

**Comment by AndreiRudenko** [comment]
Closed due inactivity

**Comment by ghost** [comment]
I guess I forgot to paste... Anyway, the issue was fixed by the devs of the game, so it can stay closed.
