### ISSUE TITLE
Building through lime on linux fails

### ISSUE THREAD

**Issue by Kade-github** [AndreiRudenko/linc_luajit#7]
No idea if i'm doing this wrong but I've been stuck on this for a while now.

When using `lime test linux -verbose` everything compiles and works just fine except the linking, which fails with this:
![image](https://user-images.githubusercontent.com/26305836/123421409-a4edca00-d571-11eb-90e7-fdb71444718f.png)

*even though when testing the path it actually **DOES** exist*

Not sure if this is me being stupid or an issue on this lib that's smth weird with lime.

Also, this only happens on mac/linux, windows builds fine and work perfectly.

Edit:
The only way I've gotten this to work on lime, is to put these in the project.xml btw:
```xml
	<haxedef name="NO_PRECOMPILED_HEADERS" />
	<haxedef name="LINC_LUA_RELATIVE_DYNAMIC_LIB"/>
```

**Comment by AndreiRudenko** [comment]
Hey, sorry for late reply. I'm not familiar with linux platform, and *.so files also not from me. I will take a look when will setup my linux system. Sorry

**Comment by Kade-github** [comment]
> Hey, sorry for late reply. I'm not familiar with linux platform, and *.so files also not from me. I will take a look when will setup my linux system. Sorry

No worries, thanks for the reply.

**Comment by Kade-github** [comment]
> Hey, sorry for late reply. I'm not familiar with linux platform, and *.so files also not from me. I will take a look when will setup my linux system. Sorry

Any update?

**Comment by Kade-github** [comment]
sorry i'm 2 days late on our anniversary

**Comment by AndreiRudenko** [comment]
Hey, looks like you need to specify paths, and *.so files for luajit need to be compiled for linux. https://luajit.org/install.html

**Comment by AndreiRudenko** [comment]
Haven't installed Linux yet to test it :( Please test it if you can, thank you

**Comment by AndreiRudenko** [comment]
Also can you test sample project, without lime? It is in test folder

**Comment by Kade-github** [comment]
I'll get my test machine up hold on a bit.

**Comment by Kade-github** [comment]
> Also can you test sample project, without lime? It is in test folder

Tried the test build, 
![image](https://user-images.githubusercontent.com/26305836/127952689-04e3de9c-1176-4558-b910-cb9fe67a09dc.png)

Same issue



> Hey, looks like you need to specify paths, and *.so files for luajit need to be compiled for linux. https://luajit.org/install.html

How would I go about this?

**Comment by Kade-github** [comment]
hello, following back up on this?

**Comment by AndreiRudenko** [comment]
This can helps, still need compiled *.so file for x86 if you use this target

**Comment by Kade-github** [comment]
> This can helps, still need compiled *.so file for x86 if you use this target

Yes this fixed the issue with it loading on lime, thanks :D
