### ISSUE TITLE
Mac version of static libs

### ISSUE THREAD

**Issue by ghost** [AndreiRudenko/linc_luajit#9]
i used homebrew to install it idk if that will work but here you go  
[google drive](https://drive.google.com/file/d/1I6PrknCV7wW07qYUV3GnHHWxOIB2awUN/view?usp=sharing)

**Comment by ghost** [comment]
also the version of it is 2.0.5 for luajit

**Comment by ghost** [comment]
also here is the full version of it [full version](https://drive.google.com/file/d/16bf2VWJknJgw_5cS6Yw3ttm7baW8wmiX/view?usp=sharing)

**Comment by AndreiRudenko** [comment]
Thank you! I will try to add it

**Comment by ghost** [comment]
your welcome

**Comment by nebulazorua** [comment]
any updates on this?

**Comment by ghost** [comment]
no sadly

**Comment by ghost** [comment]
also @nebulazorua is there a source code for your adromida engine that doesn't run on lua script?

**Comment by AndreiRudenko** [comment]
Quick blind fix for Mac. I dont have a Mac but If you can fix this, i will be awesome!

**Comment by ghost** [comment]
ima test it
